// Copyright (C) 2015 Biscrat
FILE_INCLUDE_GUARD

Class(AbstractCommandHandler)
{
    AbstractFunc(onCommand)(command:Dictionary)
    AbstractFunc(reset)()
    AbstractFunc(serialize)()
    AbstractFunc(deserialize)(dic:Dictionary)



    var _mode;

    property _noDraw { getter { return this._mode.noDraw; } }

    Constructor(mode:NovelMode) {
        checkArgs
        this._mode = mode;
    }

    Finalize() {}
}
